version: '3.8'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - local-devsu

  customer:
    container_name: customer
    build:
      context: ./customer
      dockerfile: Dockerfile
    image: customer:v1
    ports:
      - "8081:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    networks:
      - local-devsu
    volumes:
      - ./log:/log
    restart: always

  customer-products-services:
    container_name: customer-products-services
    build:
      context: ./customer-products-services
      dockerfile: Dockerfile
    image: customer-products-services:v1
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    networks:
      - local-devsu
    volumes:
      - ./log:/log
    restart: always

networks:
  local-devsu:
    driver: bridge
